Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,9 +48,16 @@ jobs:
             # Log in to Docker Hub on EC2 instance
             echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
+            # Verify that DOCKER_IMAGE has a valid format
+            if [[ ! "$DOCKER_IMAGE" =~ ^[a-z0-9]+([._-][a-z0-9]+)*\/[a-z0-9]+([._-][a-z0-9]+)*:[a-z0-9]+$ ]]; then
+              echo "Error: Invalid Docker image format: $DOCKER_IMAGE"
+              exit 1
+            fi
+
             # Pull the latest Docker image
             sudo docker pull $DOCKER_IMAGE
 
+            # Check if the container exists and is running, then stop and remove it
             if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^demo-backend\$"; then
               echo "Stopping and removing existing container..."
               sudo docker stop demo-backend
@@ -60,7 +67,7 @@ jobs:
             fi
 
             # Run the new Docker container
-            sudo docker run -d --name demo-backend -p 8080:8080 $DOCKER_IMAGE
+            sudo docker run -d --name demo-backend -p 8080:8080 $DOCKER_IMAG
           EOF
 
       # Cleanup
